// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gotocompany/shield/v1beta1/public.proto

package shieldv1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListResourceOfUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListResourceOfUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListResourceOfUserRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListResourceOfUserRequestMultiError, or nil if none found.
func (m *ListResourceOfUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListResourceOfUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Namespace

	// no validation rules for Type

	if len(errors) > 0 {
		return ListResourceOfUserRequestMultiError(errors)
	}

	return nil
}

// ListResourceOfUserRequestMultiError is an error wrapping multiple validation
// errors returned by ListResourceOfUserRequest.ValidateAll() if the
// designated constraints aren't met.
type ListResourceOfUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListResourceOfUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListResourceOfUserRequestMultiError) AllErrors() []error { return m }

// ListResourceOfUserRequestValidationError is the validation error returned by
// ListResourceOfUserRequest.Validate if the designated constraints aren't met.
type ListResourceOfUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListResourceOfUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListResourceOfUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListResourceOfUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListResourceOfUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListResourceOfUserRequestValidationError) ErrorName() string {
	return "ListResourceOfUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListResourceOfUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListResourceOfUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListResourceOfUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListResourceOfUserRequestValidationError{}

// Validate checks the field values on ListResourceOfUserResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListResourceOfUserResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListResourceOfUserResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListResourceOfUserResponseMultiError, or nil if none found.
func (m *ListResourceOfUserResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListResourceOfUserResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResources()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListResourceOfUserResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListResourceOfUserResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResources()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListResourceOfUserResponseValidationError{
				field:  "Resources",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListResourceOfUserResponseMultiError(errors)
	}

	return nil
}

// ListResourceOfUserResponseMultiError is an error wrapping multiple
// validation errors returned by ListResourceOfUserResponse.ValidateAll() if
// the designated constraints aren't met.
type ListResourceOfUserResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListResourceOfUserResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListResourceOfUserResponseMultiError) AllErrors() []error { return m }

// ListResourceOfUserResponseValidationError is the validation error returned
// by ListResourceOfUserResponse.Validate if the designated constraints aren't met.
type ListResourceOfUserResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListResourceOfUserResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListResourceOfUserResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListResourceOfUserResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListResourceOfUserResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListResourceOfUserResponseValidationError) ErrorName() string {
	return "ListResourceOfUserResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListResourceOfUserResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListResourceOfUserResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListResourceOfUserResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListResourceOfUserResponseValidationError{}
